[obligation=normative]
== Requirement Class "GeoPackage Data Store"

=== Overview

The "GeoPackage Data Store" Requirement Class defines the mandatory requirements that must be satisfied by all data stores conforming to this
CDB 2.0 GeoPackage Data Store standard.

These requirements specify:

* an encoding for datasets structured according to the https://portal.ogc.org/files/104639[_OGC CDB 2.0 - Part 1: Core_ conceptual model],
* the use of https://www.geopackage.org/spec131/index.html[_OGC GeoPackage_] as the container to store the data,
* how to store metadata required by the Core conceptual model in GeoPackages,
* use of the _deterministic hierarchical tiles grouping & indexing extension for GeoPackages_, allowing to support different use cases from
  mobile computing at the edge to large scale data repositories, by configuring how data is stored in a single GeoPackage file, or across
  multiple GeoPackages split by data layer and or tiles and
* use of the _2D Tile matrix Set extension for GeoPackages_, providing support for variable width tile matrix sets in GeoPackages.

The "GeoPackage Data Store" Requirement Class is the only mandatory Requirements Class.

include::../requirements/requirements_class_gpkg_data_store.adoc[]

=== CDB 2.x GeoDataClasses

This section should cover all datasets to be inherited from CDB 1.x
(https://docs.ogc.org/is/15-113r6/15-113r6.html), and should be registered with the OGC Naming Authority once a GeoDataClass register is set up.

NOTE: `[ogc-geodataclass:cdb-elevation]` is a safe CURIE abbreviation of http://www.opengis.net/def/geodataclass/OGC/0/cdb-elevation .

[#table_cdb_geodataclasses,reftext='{table-caption} {counter:table-num}']
.CDB GeoDataClasses
[options="header"]
|===
| GeoDataClass (safe CURIE) | CDB 1 Dataset Code | CDB 1 CS1 | CDB 1 CS2
| [ogc-geodataclass:cdb-elevation] | 001 | 001 |
| [ogc-geodataclass:cdb-imagery] | 004 |001 |
| [ogc-geodataclass:cdb-ManMade_3DModels] | 100 | 001 |
| [ogc-geodataclass:cdb-ManMade_Instanced3DModels] | 101 | 001 |
| [ogc-geodataclass:cdb-Trees_Instanced3DModels] | 101 |  003 |
| [ogc-geodataclass:cdb-Airport_Lights] | 101 | 004 | 001
| [ogc-geodataclass:cdb-RoadNetwork_Lines] | 201| 002| 003 |
| [ogc-geodataclass:cdb-Hydrography_Polygons] | 204| 002| 005
|===

NOTE: The Corona Bridge was in _ManMade_Instanced3DModels_ in the last version of the San Diego dataset, but should probably go into _ManMade_3DModels_? (there's only one)
